// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: v1.proto

package serialization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Controls how we arrive at the final probability from all the buckets at a level
type LevelSquashingFunction int32

const (
	LevelSquashingFunction_LEVEL_SQUASHING_FUNCTION_MIN  LevelSquashingFunction = 0
	LevelSquashingFunction_LEVEL_SQUASHING_FUNCTION_MEAN LevelSquashingFunction = 1
)

// Enum value maps for LevelSquashingFunction.
var (
	LevelSquashingFunction_name = map[int32]string{
		0: "LEVEL_SQUASHING_FUNCTION_MIN",
		1: "LEVEL_SQUASHING_FUNCTION_MEAN",
	}
	LevelSquashingFunction_value = map[string]int32{
		"LEVEL_SQUASHING_FUNCTION_MIN":  0,
		"LEVEL_SQUASHING_FUNCTION_MEAN": 1,
	}
)

func (x LevelSquashingFunction) Enum() *LevelSquashingFunction {
	p := new(LevelSquashingFunction)
	*p = x
	return p
}

func (x LevelSquashingFunction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LevelSquashingFunction) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_enumTypes[0].Descriptor()
}

func (LevelSquashingFunction) Type() protoreflect.EnumType {
	return &file_v1_proto_enumTypes[0]
}

func (x LevelSquashingFunction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LevelSquashingFunction.Descriptor instead.
func (LevelSquashingFunction) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{0}
}

type Algorithm int32

const (
	Algorithm_MURMURHASH_32 Algorithm = 0
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "MURMURHASH_32",
	}
	Algorithm_value = map[string]int32{
		"MURMURHASH_32": 0,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_enumTypes[1].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_v1_proto_enumTypes[1]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{1}
}

// TrackerCfg contains all the configurations related to a tracker
type TrackerCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique ID per tracker config
	TrackerId string `protobuf:"bytes,1,opt,name=tracker_id,json=trackerId,proto3" json:"tracker_id,omitempty"`
	// Version the tracker config
	ConfigVersion uint64 `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Number of buckets per level
	M uint32 `protobuf:"varint,3,opt,name=m,proto3" json:"m,omitempty"`
	// Number of levels per tracker
	L uint32 `protobuf:"varint,4,opt,name=l,proto3" json:"l,omitempty"`
	// Increment probability used on failed requests
	Pi float64 `protobuf:"fixed64,5,opt,name=pi,proto3" json:"pi,omitempty"`
	// Decrement probability used on successfull requests
	Pd float64 `protobuf:"fixed64,6,opt,name=pd,proto3" json:"pd,omitempty"`
	// Deacy rate for bucket proabilities
	Lambda float64 `protobuf:"fixed64,7,opt,name=lambda,proto3" json:"lambda,omitempty"`
	// Controls how often the internal structures are rotated
	RotationFrequency *durationpb.Duration `protobuf:"bytes,8,opt,name=rotation_frequency,json=rotationFrequency,proto3" json:"rotation_frequency,omitempty"`
	// Controls the logic for arriving at the final probability from all the buckets at a level
	LevelSquashFn LevelSquashingFunction `protobuf:"varint,9,opt,name=level_squash_fn,json=levelSquashFn,proto3,enum=fair.data.v1.LevelSquashingFunction" json:"level_squash_fn,omitempty"`
}

func (x *TrackerCfg) Reset() {
	*x = TrackerCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerCfg) ProtoMessage() {}

func (x *TrackerCfg) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerCfg.ProtoReflect.Descriptor instead.
func (*TrackerCfg) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{0}
}

func (x *TrackerCfg) GetTrackerId() string {
	if x != nil {
		return x.TrackerId
	}
	return ""
}

func (x *TrackerCfg) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *TrackerCfg) GetM() uint32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *TrackerCfg) GetL() uint32 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *TrackerCfg) GetPi() float64 {
	if x != nil {
		return x.Pi
	}
	return 0
}

func (x *TrackerCfg) GetPd() float64 {
	if x != nil {
		return x.Pd
	}
	return 0
}

func (x *TrackerCfg) GetLambda() float64 {
	if x != nil {
		return x.Lambda
	}
	return 0
}

func (x *TrackerCfg) GetRotationFrequency() *durationpb.Duration {
	if x != nil {
		return x.RotationFrequency
	}
	return nil
}

func (x *TrackerCfg) GetLevelSquashFn() LevelSquashingFunction {
	if x != nil {
		return x.LevelSquashFn
	}
	return LevelSquashingFunction_LEVEL_SQUASHING_FUNCTION_MIN
}

// Bucket holds the proability and the last update time
type Bucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probability       float64 `protobuf:"fixed64,1,opt,name=probability,proto3" json:"probability,omitempty"`
	LastUpdatedTimeMs uint64  `protobuf:"varint,2,opt,name=last_updated_time_ms,json=lastUpdatedTimeMs,proto3" json:"last_updated_time_ms,omitempty"`
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Bucket) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *Bucket) GetLastUpdatedTimeMs() uint64 {
	if x != nil {
		return x.LastUpdatedTimeMs
	}
	return 0
}

// Each level holds an array of Buckets (M Buckets)
type Level struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buckets []*Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
}

func (x *Level) Reset() {
	*x = Level{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Level) GetBuckets() []*Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

// FairData holds the tracking data containing multiple levels (L levels)
type FairData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Levels []*Level `protobuf:"bytes,1,rep,name=levels,proto3" json:"levels,omitempty"`
}

func (x *FairData) Reset() {
	*x = FairData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FairData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FairData) ProtoMessage() {}

func (x *FairData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FairData.ProtoReflect.Descriptor instead.
func (*FairData) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{3}
}

func (x *FairData) GetLevels() []*Level {
	if x != nil {
		return x.Levels
	}
	return nil
}

// AlgoParams holds the choice of Algorithm and the relevant parameters
type AlgoParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm  Algorithm `protobuf:"varint,1,opt,name=algorithm,proto3,enum=fair.data.v1.Algorithm" json:"algorithm,omitempty"`
	MurmurSeed uint32    `protobuf:"varint,2,opt,name=murmur_seed,json=murmurSeed,proto3" json:"murmur_seed,omitempty"`
}

func (x *AlgoParams) Reset() {
	*x = AlgoParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlgoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgoParams) ProtoMessage() {}

func (x *AlgoParams) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgoParams.ProtoReflect.Descriptor instead.
func (*AlgoParams) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{4}
}

func (x *AlgoParams) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_MURMURHASH_32
}

func (x *AlgoParams) GetMurmurSeed() uint32 {
	if x != nil {
		return x.MurmurSeed
	}
	return 0
}

// FairRunParameters contains the runtime params with the instance of Fair
type FairRunParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlgoParams *AlgoParams `protobuf:"bytes,1,opt,name=algo_params,json=algoParams,proto3" json:"algo_params,omitempty"`
}

func (x *FairRunParameters) Reset() {
	*x = FairRunParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FairRunParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FairRunParameters) ProtoMessage() {}

func (x *FairRunParameters) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FairRunParameters.ProtoReflect.Descriptor instead.
func (*FairRunParameters) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{5}
}

func (x *FairRunParameters) GetAlgoParams() *AlgoParams {
	if x != nil {
		return x.AlgoParams
	}
	return nil
}

// Metadata to uniquely identify a host
type HostMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostGuid       string `protobuf:"bytes,1,opt,name=host_guid,json=hostGuid,proto3" json:"host_guid,omitempty"`
	SerializedAtMs uint64 `protobuf:"varint,2,opt,name=serialized_at_ms,json=serializedAtMs,proto3" json:"serialized_at_ms,omitempty"`
}

func (x *HostMeta) Reset() {
	*x = HostMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMeta) ProtoMessage() {}

func (x *HostMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMeta.ProtoReflect.Descriptor instead.
func (*HostMeta) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{6}
}

func (x *HostMeta) GetHostGuid() string {
	if x != nil {
		return x.HostGuid
	}
	return ""
}

func (x *HostMeta) GetSerializedAtMs() uint64 {
	if x != nil {
		return x.SerializedAtMs
	}
	return 0
}

// Holds the parameters and the associated data
type FairRuntimeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Runtime *FairRunParameters `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Data    *FairData          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FairRuntimeData) Reset() {
	*x = FairRuntimeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FairRuntimeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FairRuntimeData) ProtoMessage() {}

func (x *FairRuntimeData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FairRuntimeData.ProtoReflect.Descriptor instead.
func (*FairRuntimeData) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{7}
}

func (x *FairRuntimeData) GetRuntime() *FairRunParameters {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *FairRuntimeData) GetData() *FairData {
	if x != nil {
		return x.Data
	}
	return nil
}

// FairStruct - wraps up the config, parameters and the data associated with a Fair Tracker
type FairStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cfg  *TrackerCfg      `protobuf:"bytes,1,opt,name=cfg,proto3" json:"cfg,omitempty"`
	Data *FairRuntimeData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Meta *HostMeta        `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *FairStruct) Reset() {
	*x = FairStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FairStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FairStruct) ProtoMessage() {}

func (x *FairStruct) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FairStruct.ProtoReflect.Descriptor instead.
func (*FairStruct) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{8}
}

func (x *FairStruct) GetCfg() *TrackerCfg {
	if x != nil {
		return x.Cfg
	}
	return nil
}

func (x *FairStruct) GetData() *FairRuntimeData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FairStruct) GetMeta() *HostMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_v1_proto protoreflect.FileDescriptor

var file_v1_proto_rawDesc = []byte{
	0x0a, 0x08, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x66, 0x61, 0x69, 0x72,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x02, 0x0a, 0x0a, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x43, 0x66, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a,
	0x01, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x69, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x70, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x70, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x6d,
	0x62, 0x64, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6c, 0x61, 0x6d, 0x62, 0x64,
	0x61, 0x12, 0x48, 0x0a, 0x12, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x4c, 0x0a, 0x0f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x5f, 0x73, 0x71, 0x75, 0x61, 0x73, 0x68, 0x5f, 0x66, 0x6e, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x53, 0x71, 0x75, 0x61, 0x73, 0x68, 0x69,
	0x6e, 0x67, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x53, 0x71, 0x75, 0x61, 0x73, 0x68, 0x46, 0x6e, 0x22, 0x5b, 0x0a, 0x06, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x2f, 0x0a, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x22, 0x37, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x2e, 0x0a, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22,
	0x37, 0x0a, 0x08, 0x46, 0x61, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x06, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x61,
	0x69, 0x72, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x22, 0x64, 0x0a, 0x0a, 0x41, 0x6c, 0x67, 0x6f,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x35, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69,
	0x74, 0x68, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x66, 0x61, 0x69, 0x72,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x75, 0x72, 0x6d, 0x75, 0x72, 0x5f, 0x73, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x75, 0x72, 0x6d, 0x75, 0x72, 0x53, 0x65, 0x65, 0x64, 0x22, 0x4e,
	0x0a, 0x11, 0x46, 0x61, 0x69, 0x72, 0x52, 0x75, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x39, 0x0a, 0x0b, 0x61, 0x6c, 0x67, 0x6f, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x0a, 0x61, 0x6c, 0x67, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x51,
	0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f,
	0x73, 0x74, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x47, 0x75, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x41, 0x74, 0x4d,
	0x73, 0x22, 0x78, 0x0a, 0x0f, 0x46, 0x61, 0x69, 0x72, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x39, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x69, 0x72, 0x52, 0x75, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x66, 0x61, 0x69, 0x72, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x69,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x97, 0x01, 0x0a, 0x0a,
	0x46, 0x61, 0x69, 0x72, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x2a, 0x0a, 0x03, 0x63, 0x66,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x43, 0x66,
	0x67, 0x52, 0x03, 0x63, 0x66, 0x67, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x69, 0x72, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x04, 0x6d, 0x65, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x2a, 0x5d, 0x0a, 0x16, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x53, 0x71,
	0x75, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x20, 0x0a, 0x1c, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x53, 0x51, 0x55, 0x41, 0x53, 0x48, 0x49,
	0x4e, 0x47, 0x5f, 0x46, 0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x49, 0x4e, 0x10,
	0x00, 0x12, 0x21, 0x0a, 0x1d, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x53, 0x51, 0x55, 0x41, 0x53,
	0x48, 0x49, 0x4e, 0x47, 0x5f, 0x46, 0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x45,
	0x41, 0x4e, 0x10, 0x01, 0x2a, 0x1e, 0x0a, 0x09, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x55, 0x52, 0x4d, 0x55, 0x52, 0x48, 0x41, 0x53, 0x48, 0x5f,
	0x33, 0x32, 0x10, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x74, 0x6d, 0x69, 0x68, 0x69, 0x72, 0x2f, 0x66, 0x61, 0x69, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_proto_rawDescOnce sync.Once
	file_v1_proto_rawDescData = file_v1_proto_rawDesc
)

func file_v1_proto_rawDescGZIP() []byte {
	file_v1_proto_rawDescOnce.Do(func() {
		file_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_proto_rawDescData)
	})
	return file_v1_proto_rawDescData
}

var file_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_proto_goTypes = []any{
	(LevelSquashingFunction)(0), // 0: fair.data.v1.LevelSquashingFunction
	(Algorithm)(0),              // 1: fair.data.v1.Algorithm
	(*TrackerCfg)(nil),          // 2: fair.data.v1.TrackerCfg
	(*Bucket)(nil),              // 3: fair.data.v1.Bucket
	(*Level)(nil),               // 4: fair.data.v1.Level
	(*FairData)(nil),            // 5: fair.data.v1.FairData
	(*AlgoParams)(nil),          // 6: fair.data.v1.AlgoParams
	(*FairRunParameters)(nil),   // 7: fair.data.v1.FairRunParameters
	(*HostMeta)(nil),            // 8: fair.data.v1.HostMeta
	(*FairRuntimeData)(nil),     // 9: fair.data.v1.FairRuntimeData
	(*FairStruct)(nil),          // 10: fair.data.v1.FairStruct
	(*durationpb.Duration)(nil), // 11: google.protobuf.Duration
}
var file_v1_proto_depIdxs = []int32{
	11, // 0: fair.data.v1.TrackerCfg.rotation_frequency:type_name -> google.protobuf.Duration
	0,  // 1: fair.data.v1.TrackerCfg.level_squash_fn:type_name -> fair.data.v1.LevelSquashingFunction
	3,  // 2: fair.data.v1.Level.buckets:type_name -> fair.data.v1.Bucket
	4,  // 3: fair.data.v1.FairData.levels:type_name -> fair.data.v1.Level
	1,  // 4: fair.data.v1.AlgoParams.algorithm:type_name -> fair.data.v1.Algorithm
	6,  // 5: fair.data.v1.FairRunParameters.algo_params:type_name -> fair.data.v1.AlgoParams
	7,  // 6: fair.data.v1.FairRuntimeData.runtime:type_name -> fair.data.v1.FairRunParameters
	5,  // 7: fair.data.v1.FairRuntimeData.data:type_name -> fair.data.v1.FairData
	2,  // 8: fair.data.v1.FairStruct.cfg:type_name -> fair.data.v1.TrackerCfg
	9,  // 9: fair.data.v1.FairStruct.data:type_name -> fair.data.v1.FairRuntimeData
	8,  // 10: fair.data.v1.FairStruct.meta:type_name -> fair.data.v1.HostMeta
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_v1_proto_init() }
func file_v1_proto_init() {
	if File_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TrackerCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Bucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Level); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FairData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AlgoParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FairRunParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*HostMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FairRuntimeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FairStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_proto_goTypes,
		DependencyIndexes: file_v1_proto_depIdxs,
		EnumInfos:         file_v1_proto_enumTypes,
		MessageInfos:      file_v1_proto_msgTypes,
	}.Build()
	File_v1_proto = out.File
	file_v1_proto_rawDesc = nil
	file_v1_proto_goTypes = nil
	file_v1_proto_depIdxs = nil
}
